package BankApp;

/**
* BankApp/AccountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Wednesday, September 28, 2022 12:35:00 AM CAT
*/

public final class AccountHolder implements org.omg.CORBA.portable.Streamable
{
  public BankApp.Account value = null;

  public AccountHolder ()
  {
  }

  public AccountHolder (BankApp.Account initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankApp.AccountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankApp.AccountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankApp.AccountHelper.type ();
  }

}
