package BankApp;


/**
* BankApp/AccountPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Wednesday, September 28, 2022 12:35:00 AM CAT
*/

public abstract class AccountPOA extends org.omg.PortableServer.Servant
 implements BankApp.AccountOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("create", new java.lang.Integer (0));
    _methods.put ("deposit", new java.lang.Integer (1));
    _methods.put ("withdraw", new java.lang.Integer (2));
    _methods.put ("balance", new java.lang.Integer (3));
    _methods.put ("login", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BankApp/Account/create
       {
         String name = in.read_string ();
         int pass = in.read_long ();
         int $result = (int)0;
         $result = this.create (name, pass);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // BankApp/Account/deposit
       {
         float amount = in.read_float ();
         int number = in.read_long ();
         this.deposit (amount, number);
         out = $rh.createReply();
         break;
       }

       case 2:  // BankApp/Account/withdraw
       {
         float amount = in.read_float ();
         int number = in.read_long ();
         String $result = null;
         $result = this.withdraw (amount, number);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // BankApp/Account/balance
       {
         int number = in.read_long ();
         float $result = (float)0;
         $result = this.balance (number);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 4:  // BankApp/Account/login
       {
         int number = in.read_long ();
         int pass = in.read_long ();
         boolean $result = false;
         $result = this.login (number, pass);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BankApp/Account:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Account _this() 
  {
    return AccountHelper.narrow(
    super._this_object());
  }

  public Account _this(org.omg.CORBA.ORB orb) 
  {
    return AccountHelper.narrow(
    super._this_object(orb));
  }


} // class AccountPOA
