package BankApp;


/**
* BankApp/BankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Wednesday, September 28, 2022 12:35:00 AM CAT
*/

public interface BankOperations 
{
  BankApp.Account create ();
} // interface BankOperations
