package BankApp;


/**
* BankApp/DataOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Wednesday, September 28, 2022 12:35:00 AM CAT
*/

public interface DataOperations 
{
  int insert (String name, int pass);
  BankApp.Account read (int number);
  int getPass (int number);
  float getBalance (int number);
  void update (float balance, int number);
} // interface DataOperations
