package BankApp;

/**
* BankApp/DataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Wednesday, September 28, 2022 12:35:00 AM CAT
*/

public final class DataHolder implements org.omg.CORBA.portable.Streamable
{
  public BankApp.Data value = null;

  public DataHolder ()
  {
  }

  public DataHolder (BankApp.Data initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BankApp.DataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BankApp.DataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BankApp.DataHelper.type ();
  }

}
