package BankApp;


/**
* BankApp/DataPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Wednesday, September 28, 2022 12:35:00 AM CAT
*/

public abstract class DataPOA extends org.omg.PortableServer.Servant
 implements BankApp.DataOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insert", new java.lang.Integer (0));
    _methods.put ("read", new java.lang.Integer (1));
    _methods.put ("getPass", new java.lang.Integer (2));
    _methods.put ("getBalance", new java.lang.Integer (3));
    _methods.put ("update", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BankApp/Data/insert
       {
         String name = in.read_string ();
         int pass = in.read_long ();
         int $result = (int)0;
         $result = this.insert (name, pass);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // BankApp/Data/read
       {
         int number = in.read_long ();
         BankApp.Account $result = null;
         $result = this.read (number);
         out = $rh.createReply();
         BankApp.AccountHelper.write (out, $result);
         break;
       }

       case 2:  // BankApp/Data/getPass
       {
         int number = in.read_long ();
         int $result = (int)0;
         $result = this.getPass (number);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // BankApp/Data/getBalance
       {
         int number = in.read_long ();
         float $result = (float)0;
         $result = this.getBalance (number);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 4:  // BankApp/Data/update
       {
         float balance = in.read_float ();
         int number = in.read_long ();
         this.update (balance, number);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BankApp/Data:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Data _this() 
  {
    return DataHelper.narrow(
    super._this_object());
  }

  public Data _this(org.omg.CORBA.ORB orb) 
  {
    return DataHelper.narrow(
    super._this_object(orb));
  }


} // class DataPOA
