package BankApp;


/**
* BankApp/AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Wednesday, September 28, 2022 12:35:00 AM CAT
*/

public interface AccountOperations 
{
  int create (String name, int pass);
  void deposit (float amount, int number);
  String withdraw (float amount, int number);
  float balance (int number);
  boolean login (int number, int pass);
} // interface AccountOperations
